version: 0.2
os: linux
files:
  - source: /
    destination: /home/ubuntu/prueba-aws-ms-seguridad
hooks: 
  AfterInstall:
    - location: deploy/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: deploy/application_start.sh
      timeout: 300
